#!/usr/bin/env bash

w1=$(tput setaf 2)
w2=$(tput setaf 3)
w3=$(tput setaf 7)

menu() {
    local m="
    ---------------------------------
    Fbct                         MENU
    ---------------------------------


    ---------------------------------
    Malik Kurosaki              v0001
    ---------------------------------
    "

    echo $w2"$m"$w3
}

run() {
    case $1 in
    -s) cd xserver && nodemon server.js ;;
    -c) flutter run -d chrome ;;
    *) echo "perintah run hanya -c dan -s" ;;
    esac
}

push() {
    echo $w2
    echo "coba build"
    flutter build web --release
    rm -r build/web/assets/images
    cp -r build/web/assets/assets/images build/web/assets/images
    git add .
    git commit -m "baru"
    git push origin main
    echo $w3
}

perintah() {
    case $1 in
    push) push ;;
    run) run $2 ;;
    spl) flutter pub run flutter_native_splash:create ;;
    start) cd xserver && pm2 start server.js --watch --name fbct ;;
    *) menu ;;
    esac
}

[[ ! -z $1 ]] && perintah $1 $2 || menu
